apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kiali
    version: v1
  name: kiali
  namespace: service-mesh
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kiali
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kiali
    spec:
      containers:
        - image: harbor.cloud2go.cn/cloudos-dev/kiali:0.0.3
          args:
            - kiali
            - --context=cluster03
            - --prometheus=http://prometheus.prometheus-operator:9090
            #- --prometheus=http://prometheus.istio-system:9090
          imagePullPolicy: Always
          name: kiali
          resources: { }
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: kiali-service-account
      serviceAccountName: kiali-service-account

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: kiali
  name: kiali
  namespace: service-mesh
spec:
  ports:
    - name: http-8080
      port: 8080
      protocol: TCP
  selector:
    app: kiali
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: { }

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: kiali
  name: kiali
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - endpoints
      - namespaces
      - nodes
      - pods
      - pods/log
      - replicationcontrollers
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
      - apps
    resources:
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - config.istio.io
      - networking.istio.io
      - authentication.istio.io
      - rbac.istio.io
      - security.istio.io
    resources:
      - '*'
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - monitoring.kiali.io
    resources:
      - monitoringdashboards
    verbs:
      - get
      - list

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: kiali
  name: kiali
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kiali
subjects:
  - kind: ServiceAccount
    name: kiali-service-account
    namespace: service-mesh


---

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: kiali
  name: kiali-service-account
  namespace: service-mesh


---

# istio gateway
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: kiali-gateway
  namespace: service-mesh
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - '*'
      port:
        name: http
        number: 20001
        protocol: HTTP

---

# virtualservices istio


apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  generation: 1
  name: kiali
  namespace: service-mesh
spec:
  gateways:
    - kiali-gateway
  hosts:
    - '*'
  http:
    - route:
        - destination:
            host: kiali
            port:
              number: 8080


