apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kiali
    version: v1
  name: kiali
  namespace: service-mesh
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kiali
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kiali
    spec:
      containers:
        - image: harbor.cloud2go.cn/cloudos-dev/kiali:0.0.1
          imagePullPolicy: Always
          name: kiali
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler


---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: kiali
  name: kiali
  namespace: service-mesh
spec:
  ports:
    - name: http-8080
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: kiali
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

---

